
backend:
  name: git-gateway
  branch: master
media_folder: /public/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: auteurs
    label: Auteurs
    folder: "content/auteurs"
    create: true
    fields:
      - {name: naam, label: Naam}

  - name: tags
    label: Tags
    folder: "content/tags"
    create: true
    fields:
      - {name: naam, label: Naam}


  - name: photo's
    label: Photo's
    folder: "content/photo's"
    create: true
    fields:
      - {name: naam, label: Naam}
      - {label: "Image", name: "image", widget: "image"}


  - name: posts
    label: Posts
    folder: "content/posts"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post.template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "Subtitle", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - name: headerPhoto
        label: HeaderPhoto
        widget: relation
        collection: photo's
        searchFields: [naam]
        valueField: image
        required: true

      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Onderwerp"
        name: "onderwerp"
        widget: "select"
        options: ["history","human","nature","quirky","space","tech"]
      - name: auteur
        label: Auteur
        widget: relation
        collection: auteurs
        searchFields: [naam]
        valueField: naam
      - name: tags
        label: Tags
        widget: relation
        collection: tags
        searchFields: [naam]
        multiple: true
        valueField: naam
        required: false
      - name: photo's
        label: Photo's
        widget: relation
        collection: photo's
        searchFields: [naam]
        multiple: true
        valueField: naam
        required: false


